{{- include "chartname.validate-pdb" . -}}
{{- if .Values.security.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  {{- if .Values.security.pdb.minAvailable }}
  minAvailable: {{ .Values.security.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.security.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.security.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chartname.selectorLabels" . | nindent 6 }}
{{- end }}
