{{- if .Values.observability.openTelemetry.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chartname.fullname" . }}-otel-collector
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
rules:
- apiGroups: 
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes/spec
  - pods
  - nodes
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - nodes/proxy
  - resourcequota
  - services
  verbs: 
  - get
  - list
  - watch
- apiGroups: 
  - apps
  resources: 
  - daemonsets
  - deployments
  - statefulsets
  - replicasets
  verbs: 
  - get
  - list
  - watch
- apiGroups: 
  - autoscaling
  resources: 
  - horizontalpodautoscalers
  verbs: 
  - get
  - list
  - watch
{{- end }}
