{{- if .Values.persistence.enabled -}}
{{- range .Values.persistence.claims -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chartname.fullname" $ }}-{{ .name }}
  labels:
    {{- include "chartname.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
