{{- if .Values.eso.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
    app.kubernetes.io/name: secret-creator
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.eso.secretStoreRef.name }}
    kind: {{ .Values.eso.secretStoreRef.kind }}
  target:
    name: {{ .Values.eso.target.name | default (include "chartname.fullname" .) }}
    creationPolicy: {{ .Values.eso.target.creationPolicy }}
  {{- with .Values.eso.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.eso.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
