{{- if and .Values.networking.gateway.enabled .Values.networking.gateway.installCRDs }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chartname.fullname" . }}-crd-manager
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chartname.fullname" . }}-crd-manager-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chartname.fullname" . }}-crd-manager-binding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chartname.fullname" . }}-crd-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "chartname.fullname" . }}-crd-manager
    namespace: {{ .Release.Namespace }}
{{- end }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chartname.fullname" . }}-gateway-crd-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "chartname.fullname" . }}-crd-manager
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Instalando Gateway API CRDs..."
          kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
      restartPolicy: OnFailure