{{- if .Values.scaling.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.workload.kind }}
    name: {{ include "chartname.fullname" . }}
  minReplicas: {{ .Values.scaling.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.scaling.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.scaling.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaling.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.scaling.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaling.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
