{{- if .Values.config.secretStore.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  provider:
    oracle:
      vault: {{ required "secretStore.vaultOCID is required" .Values.config.secretStore.vaultOCID }}
      region: {{ .Values.config.secretStore.region }}
      principalType: {{ .Values.config.secretStore.principalType | default "InstancePrincipal" }}
      {{- if eq .Values.config.secretStore.principalType "UserPrincipal" }}
      auth:
        user: {{ .Values.config.secretStore.user }}
        tenancy: {{ .Values.config.secretStore.tenancy }}
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
          fingerprint:
            name: oracle-secret
            key: fingerprint
      {{- end }}
{{- end }}
