{{/*
Reflector TLS Secrets
Iterates over ingress and ingressInternal TLS configurations.
If 'reflectsFrom' is defined, creates a Secret with Reflector annotation.
*/}}
{{- $tlsConfigs := list }}
{{- if and .Values.ingress.enabled .Values.ingress.tls }}
  {{- $tlsConfigs = concat $tlsConfigs .Values.ingress.tls }}
{{- end }}
{{- if and .Values.ingressInternal.enabled .Values.ingressInternal.tls }}
  {{- $tlsConfigs = concat $tlsConfigs .Values.ingressInternal.tls }}
{{- end }}

{{- range $tlsConfigs }}
{{- if .reflectsFrom }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: {{ .reflectsFrom | quote }}
type: kubernetes.io/tls
data:
  # Base64 encoded dummy values to satisfy Secret validation before Reflector syncs
  tls.crt: dGxzLmNydA==
  tls.key: dGxzLmtleQ==
{{- end }}
{{- end }}
