{{- if .Values.config.secretStore.enabled -}}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.config.secretStore.provider | nindent 4 }}
{{- end }}
